sudo: false
addons:
  apt:
    packages:
      - libgd-gd2-perl
script: |
  set -e
  if [ "${TRAVIS_SECURE_ENV_VARS}" = "true" ]; then
    git config --global user.name  "Travis CI"
    git config --global user.email travis@travis-ci.org

    openssl aes-256-cbc -K $encrypted_bbb57686d0f3_key -iv $encrypted_bbb57686d0f3_iv \
      -in .ssh-deploy-key.enc -out ~/.ssh/id_rsa -d
    chmod 0600 ~/.ssh/id_rsa

    export REMOTE=git@github.com:solvespace/website
    if [ -n "${TRAVIS_TAG}" ]; then
      export SUBDIR="${TRAVIS_TAG}"
      export VERSION="release ${TRAVIS_TAG/v/}"
    else
      export SUBDIR="${TRAVIS_BRANCH}"
      export VERSION="development branch <tt>${TRAVIS_BRANCH}</tt>"
    fi
    make gh-pages
    echo "Deployed to https://solvespace.github.io/website/${SUBDIR}/"
  else
    make
  fi
