sudo: false
addons:
  apt:
    packages:
      - libgd-gd2-perl
      - w3c-linkchecker
script:
  - make
  - checklink -qr html/index.html -X 'html/forum.html$' | tee checklink.txt
  - if grep "Code:\ 404" checklink.txt >/dev/null; then exit 1; fi
after_success:
  - if [ "${TRAVIS_SECURE_ENV_VARS}" != "true" ]; then exit 0; fi
  - if [ "${TRAVIS_BRANCH}" != "master" ]; then exit 0; fi
  - echo "$DEPLOY_KEY" | base64 -d >~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
  - git config --global user.name  "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - make gh-pages REMOTE=git@github.com:solvespace/solvespace-web
  - echo "Deployed to https://solvespace.github.io/solvespace-web/"
